import type { Metadata } from "next";
import { K2D } from "next/font/google"; 
import "./globals.css"; // แนะนำให้ย้ายมาบรรทัดนี้ หรือบนสุด
import DashboardWrapper from "./dashboardWrapper";
import { Providers } from "./providers";

// ตั้งค่า K2D
const k2d = K2D({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-k2d", // (Optional) เผื่ออยากใช้ผ่าน CSS Variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* ต้องใส่ k2d.className ลงใน body ไม่งั้นฟอนต์ไม่ติด */}
      <body className={k2d.className}>
        <Providers>
           <DashboardWrapper>{children}</DashboardWrapper>
        </Providers>
      </body>
    </html>
  );
}