import type { Metadata } from "next";
import { K2D } from "next/font/google"; 
import "./globals.css"; // แนะนำให้ย้ายมาบรรทัดนี้ หรือบนสุด
import DashboardWrapper from "./dashboardWrapper";
import { Providers } from "./providers";

import {getServerSession} from 'next-auth'                      //get sesssion ของ singin
import SessionProvider from './(components)/SeecionProviders'     //get sesssion ของ singin



// 2. ตั้งค่า K2D (กำหนด weight ที่ต้องการใช้)
const k2d = K2D({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-k2d", // (Optional) เผื่ออยากใช้ผ่าน CSS Variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ...existing code...
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()   //get sesssion ของ singin
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SessionProvider session={session}>
        <Providers>
           <DashboardWrapper>{children}</DashboardWrapper>
        </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}