import type { Metadata } from "next";
import "./globals.css";
import { K2D } from "next/font/google"; // 1. เปลี่ยน import เป็น K2D
import DashboardWrapper from "./dashboardWrapper";
import { Providers } from "./providers";

// 2. ตั้งค่า K2D (กำหนด weight ที่ต้องการใช้)
const k2d = K2D({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
           <DashboardWrapper>{children}</DashboardWrapper>
        </Providers>
      </body>
    </html>
  );
}